spring.application.name=consumer
spring.rabbitmq.port=5672
spring.rabbitmq.host=localhost
spring.rabbitmq.username=user
spring.rabbitmq.password=password
logging.level.org.springframework.amqp=DEBUG

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

server.port=8085

eureka.client.serviceUrl.defaultZone= http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true