spring.application.name=pelanggan
server.port=8088
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

eureka.client.serviceUrl.defaultZone= http://ms-eureka:8761/eureka/
eureka.instance.prefer-ip-address=true
